config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'home#index'

  resources :users, only: [:show]
  resources :events do
    resources :comments
    resources :votes, only: [] do
      collection do
        put :vote
        put :unvote
      end
    end
    collection do
      get :near_me
    end
  end
  
  resources :donations
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.featured.limit(6).includes(:donations)
    @hotEvent = Event.enable.first
    @realtime_notifications = Notification.real_time
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<ul>
  <li>
    <div class="special-event">
      <div id="ri-grid" class="ri-grid">
        <ul>
          <% Event.order(created_at: :desc).each do |event| %>
            <li>
              <%= link_to event_path(event) do %>
                <%= image_tag event.thumbnail_url %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="event-contents text-center">
        <h3 id="ideal-number"><%= Event.all.size %></h3>
        <p>Ý tưởng đã được khởi tạo</p>
        <a class="button icon main big text-left" href="<%= new_event_path %>">Tạo ý tưởng</a>
      </div>
    </div>
  </li>
</ul>

<div class="idea-blocks wrapper">
  <div class="list inline top">
    <h3><%= t("common.featured_idea") %></h3>
    <% @events.each do |e| %>
      <div class="block inline top">
        <%= image_tag e.thumbnail_url =%>
        <a class="button animation main" href=<%= event_path(e) %>>View idea</a>
        <h4><%= truncate(e.name.mb_chars.capitalize.to_s, length: 20) %></h4>
        <p><%= truncate(e.short_description.mb_chars.capitalize.to_s, length: 350) %></p>
        <a class="love-us" href="#"><%= e.votes.size %> <i class="fa fa-heart"></i></a>
        <ul class="more">
          <li><i class="fa fa-user"></i>Tác giả: <strong><%= e.user.full_name %></strong></li>
          <li><i class="fa fa-map-marker"></i>Địa điểm: <strong><%= e.location %></strong></li>
          <li><i class="fa fa-calendar"></i>Ngày hết hạn: <strong><%= e.donation_due_date.strftime("%d/%m/%Y") %></strong></li>
        </ul>
        <div class="progress-bar">
          <div class="bar animation" style="width:<%= (e.donations.sum(:amount) / e.required_amount)*100 %>%;"></div>
          <span class="percent"><%= (e.donations.sum(:amount) / e.required_amount).round(2) *100 %>%</span>
          <span class="backer"><strong><%= e.donations.size %></strong>người ủng </span>
          <span class="raised">Số tiền: <strong><%= number_to_currency(e.donations.sum(:amount), format: "%n VNĐ") %></strong></span>
        </div>
      </div>
    <% end %>
  </div>

  <div class="real-event inline top">
    <h3><%= t("common.realtime_event") %></h3>
    <ul>
      <% @realtime_notifications.each do |notification| %>
        <li>
          <%= image_tag notification.event.thumbnail_url %>
          <div class="content">
            <h4><%= link_to truncate(notification.event.name.mb_chars.capitalize.to_s, length: 25), event_path(notification.event) %></h4>
            <p><%= raw(notification.message) %></p>
            <span><%= time_ago_in_words(notification.created_at) %></span>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="idea-near-me">
  <h3 class="wrapper"><%= t("common.idear_near_me") %></h3>
  <div id="map" class="idea-map"></div>
</div>

<div class="summary">
  <ul class="wrapper">
    <li class="inline top">
      <h4><%= Event.enable.size %></h4>
      <span><strong>ý tưởng</strong> đã được khởi tạo</span>
    </li>
    <li class="inline top">
      <h4><%= number_to_currency(Donation.sum(:amount).floor, format: "%n VNĐ") %></h4>
      <span> đã được <strong>ủng hộ</strong></span>
    </li>
    <li class="inline top">
      <h4><%= User.all.size %></h4>
      <span><strong>nhà tự thiện</strong> đã tham gia quyên góp</span>
    </li>
  </ul>
</div>