config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'home#index'

  resources :users, only: [:show]
  resources :events do
    resources :comments
    resources :votes, only: [] do
      collection do
        put :vote
        put :unvote
      end
    end
    collection do
      get :near_me
    end
  end
  
  resources :donations
end

app/models/event.rb
class Event < ActiveRecord::Base
  geocoded_by :location   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  after_update :notify_system
  before_save :check_over

  belongs_to :user
  belongs_to :category

  has_many :donations, as: :donatable
  has_many :votes, as: :votable
  has_many :comments
  has_many :participations
  has_many :participants, through: :participations, source: :event
  has_many :notifications, dependent: :destroy

  validates :category, presence: true

  scope :enable, -> { where(enable: true) }
  scope :featured, -> { enable.joins(:votes).group("events.id").order('count(events.id) DESC') }
  scope :near_me, -> (lat, lon) { Event.near([lat, lon], 100).limit(10) }

  def vote_by!(user)
    # create a new vote associating user and photo
    raise "Already voted" if voted_by?(user)
    votes.find_or_create_by!(voter: user)
  end

  def unvote_by!(user)
    raise "Not yet voted" unless voted_by?(user)
    votes.where(voter: user).first.destroy
  end

  def voted_by?(user)
    votes.exists?(voter: user)
  end

  def vote_count
    votes.size
  end

  def send_sms
    message = "\nXin chúc mừng:\n"
    message += "Ý tưởng của bạn đã quyên góp đủ số tiền.\n"
    message += "\nÝ tưởng: #{name}"
    message += "\nTổng số tiền nhận được: #{donations.sum(:amount)} VNĐ"
    message += "\n\nHãy thực hiện ý tưởng của bạn vì cộng đồng"
    @client = Twilio::REST::Client.new "AC1f944d7f633a1bd6d3a87d6ca62ef497", "d323885b3cfdcb0aaa079ba5b60998c3"
    @client.messages.create(
      from: "+12017318643",
      to: "+841289816416",
      body: message
    )
  end

  def is_valid?
    donations.sum(:amount) >= required_amount
  end

  private
  def notify_system
    if changes['enable']
      notifications.create(message: "vừa được khởi tạo")
    end
  end

  def check_over
    if success
      SendSmsWorker.new.perform(id)
      SendEmailEventCloseWorker.new.perform(id)
    end
    true
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :near_me]
  before_action :load_categories, only: [:new, :edit]
  before_action :get_event, only: [:edit, :show, :update]

  def index
    keyword = params[:keyword]
    if keyword == "Tại đây"

    else
      @events = Event.where("name LIKE ?", "%#{keyword}%")
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.new event_params
    event.user = current_user
    thumbnail_file_path = "abra/event/thumbnail/#{Time.now.strftime("%Y/%m/%d/")}#{SecureRandom.hex(13)}#{File.extname(params[:event][:thumbnail_url].original_filename)}"
    obj = S3_BUCKET.object(thumbnail_file_path)
    obj.upload_file(params[:event][:thumbnail_url].tempfile, {
      acl: 'public-read'
    })

    event.thumbnail_url = obj.public_url

    if event.save
      flash[:success] = "Ý tưởng được tạo thành công."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      flash[:success] = "Update event successfully"
      redirect_to @event
    else
      flash[:error] = @event.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def near_me
    @events = Event.near_me(params[:lat], params[:lon])
    render json: @events
  end

  private
  def event_params
    params.require(:event).permit(:name,
      :category_id, :location, :city, :lat, :lng,
      :start_at, :short_description, :number_of_participant,
      :required_amount, :donation_due_date, :story, :thumbnail_url)
  end

  def get_event
    @event = Event.enable.find(params[:id])
  end

  def load_categories
    @categories = Category.all_enable
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => {:multipart => true}  do |f| %>
    <div class="double row1">
      <%= f.input :name, :label => "Tên sự kiện", autofocus: true %>
      <%= f.input :category_id, :label => "Thể loại", collection: @categories %>
    </div>
    <div class="double row2">
      <%= f.input :required_amount, :label => "Số tiền cần giúp đỡ" %>
      <%= f.input :number_of_participant, :label => "Số lượng người tham gia" %>
    </div>
    <%= f.input :short_description, :label => "Giới thiệu ", as: :text %>
    <%= f.input :location, :label => "Địa điểm", input_html: { id: "autocomplete", onFocus: "geolocate()" } %>
    <%= f.input :phone_number, :lable => "Số điện thoại:", as: :text %>

    <%= f.input :city, :as => :hidden, input_html: { id: "city" }  %>

    <%= f.input :latitude, :as => :hidden, input_html: { id: "lat" }  %>

    <%= f.input :longitude, :as => :hidden, input_html: { id: "lng" }  %>

    <%= f.input :thumbnail_url, :label => "Hình ảnh", as: :file %>

    <h4>Thời gian</h4>

    <%= f.input :start_at, :label => "Thời gian bắt đầu" %>

    <%= f.input :donation_due_date, :label => "Ngày hết hạn ủng hộ" %>

    <h4>Thông tin chi tiết</h4>

    <%= f.input :story, input_html: { id: "edit" } %>

    <div class="buttons">
      <%= f.button :submit, "Xem Trước", class: "button sub inline top" %>    <%= f.button :submit , class: "button main inline top" %>
    </div>

<% end %>

<script>
  function initAutocomplete() {
    input = document.getElementById('autocomplete');
    google.maps.event.addDomListener(input, 'keydown', function(e) {
      if (e.keyCode == 13) {
          e.preventDefault();
      }
    });

    autocomplete = new google.maps.places.Autocomplete(
      (input),
      {types: ['geocode']}
    );

    autocomplete.addListener('place_changed', function(e) {
      place = autocomplete.getPlace();

      cityInput = document.getElementById('city');
      latInput = document.getElementById('lat');
      longInput = document.getElementById('lng');

      for (var i = 0; i < place.address_components.length; i++) {
        var addressType = place.address_components[i].types[0];
        if (addressType == 'administrative_area_level_1') {
          cityInput.value = place.address_components[i]['long_name'];
          break;
        }
      }

      latInput.value = place.geometry.location.lat();
      longInput.value = place.geometry.location.lng();
    });
  }

  function geolocate() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var geolocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        var circle = new google.maps.Circle({
          center: geolocation,
          radius: position.coords.accuracy
        });
        autocomplete.setBounds(circle.getBounds());
      });
    }
  }

  $(function() {
    $('#edit').froalaEditor({
      width: '764',
      height: '300'
    });
  });
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkKcB2Vfei2ySQzJ17rfXX_19IGzJaxms&signed_in=true&libraries=places&callback=initAutocomplete" async defer></script>

app/views/events/edit.html.erb
<h1>Chỉnh sửa sự kiện</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events</h1>

app/views/events/new.html.erb
<div class="wrapper create-event">
  <h3>Tạo sự kiện</h3>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="special-event event-detail-thumbnail">
  <ul>
    <li>
      <%= image_tag @event.thumbnail_url %>
      <div class="event-contents text-center">
        <h3><%= @event.name %></h3>
        <p><%= truncate(@event.short_description, length: 350) %>.</p>
      </div>
    </li>
  </ul>
</div>

<div class="contents wrapper">
  <div class="text inline top">
    <h3>Nội dung</h3>
    <div class="block description">
      <%= @event.short_description %>
    </div>
    <h3>Chương trình</h3>
    <div class="block timeline">
      <%= raw(@event.story) %>
    </div>
    <h3>Bản đồ</h3>
    <div class="block map" id="mapdetail"></div>
    <h3>Bình luận</h3>
    <div class="block list-comments">
      <%= render 'comments/comment_list' %>
    </div>
  </div>
  <div class="bar inline top">
    <div class="block">
      <div class="progress-bar">
        <div class="bar-line animation" style="width:<%= (@event.donations.sum(:amount) / @event.required_amount).round(2) *100 %>%"></div>
        <span class="percent"><%= (@event.donations.sum(:amount) / @event.required_amount).round(2) *100 %>%</span>
      </div>
      <div class="line">
        <label>Số tiền cần thiết</label>
        <span class="money1"><%= number_to_currency(@event.required_amount, format: "%n VNĐ") %></span>
      </div>
      <div class="line">
        <label>Số tiền thu được</label>
        <span class="money2"><%= number_to_currency(@event.donations.sum(:amount), format: "%n VNĐ") %></span>
      </div>
      <div class="line">
        <label>Ngày kết thúc</label>
        <span><%= @event.donation_due_date.strftime("%d/%m/%Y") %></span>
      </div>
      <% if signed_in? && !@event.is_valid? %>
        <center>
          <%= form_tag donations_path, id: "donation_form" do |f| %>
            <%= hidden_field(:donation, :event_id, value: @event.id) %>
            <%= number_field(:donation, :amouth, id: "amount") %>
            <button id="customButton">Ủng Hộ</button>
            <script>
              $(document).ready(function(){
                var handler = StripeCheckout.configure({
                  key: "<%= Rails.configuration.stripe[:publishable_key] %>",
                  image: "<%= image_path 'logo.png' %>",
                  locale: 'auto',
                  token: function(token) {
                    $('#donation_form').submit();
                  }
                });

                $('#customButton').on('click', function(e) {
                  var amount = $("#amount").val();
                  handler.open({
                    name: 'Ủng hộ <%= @event.name %>',
                    description: '<%= current_user.email %>',
                    amount: amount,
                    currency: 'VND'
                  });
                  e.preventDefault();
                });

                // Close Checkout on page navigation
                $(window).on('popstate', function() {
                  handler.close();
                });
              });
            </script>
          <% end %>
        </center>
      <% end %>
    </div>

    <div class="block votes">
      <%= render "votes/votes" %>
    </div>

    <div class="block social">
      <a class="button facebook icon"><i class="fa fa-facebook"></i>facebook</a>
      <a class="button twitter icon"><i class="fa fa-twitter"></i>twitter</a>
    </div>

    <div class="block donors">
      <h4><%= t("common.donors") %></h4>
      <ul>
        <% @event.donations.each do |donation| %>
          <li>
            <%= image_tag donation.donor.avatar_url %>
            <span><%= donation.donor.email %></span>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

<script>
  $(document).ready(function(data){
    function initialize() {
      var bangalore = { lat: parseFloat("<%= @event.latitude %>"), lng: parseFloat("<%= @event.longitude %>") };
      var map = new google.maps.Map(document.getElementById('mapdetail'), {
        zoom: 15,
        scrollwheel: false,
        center: bangalore
      });

      var marker = new google.maps.Marker({
        position: bangalore,
        map: map
      });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
  });
</script>