config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'home#index'

  resources :users, only: [:show]
  resources :events do
    resources :comments
    resources :votes, only: [] do
      collection do
        put :vote
        put :unvote
      end
    end
    collection do
      get :near_me
    end
  end
  
  resources :donations
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
  belongs_to :voter, polymorphic: true
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_event, only: [:vote, :unvote]
  respond_to :js

  def vote
    @event.vote_by!(current_user)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def unvote
    @event.unvote_by!(current_user)
  end

  private
  def get_event
    @event = Event.find(params[:event_id])
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_votes.html.erb
<span class="inline middle"><%= @event.reload.vote_count %> người thích</span>
<% if signed_in? %>
  <% if @event.voted_by?(current_user) %>
    <%= link_to unvote_event_votes_path(@event), method: :put, remote: true, class: "button sub inline middle" do %>
      <i class="fa fa-thumbs-o-down"></i>
    <% end %>
  <% else %>
    <%= link_to vote_event_votes_path(@event),class: "button main inline middle", method: :put, remote: true do%>
      <i class="fa fa-thumbs-o-up"></i>
    <% end %>
  <% end %>
<% end %>

app/views/votes/unvote.js.erb
$(document).ready(function(event) {
  $('.votes').html("<%= j(render 'votes') %>");
});

app/views/votes/vote.js.erb
$(document).ready(function(event) {
  $('.votes').html("<%= j(render 'votes') %>");
});